### ISSUE TITLE
 can I reprint?

### ISSUE THREAD

**Issue by lkqyyds** [gbl/InfiniteVillagerTrading#3]
Hello, can I reprint this module to www.mcbbs.net？

Mcbbs is a well-known forum in China. Rest assured that I will only use your official download link (GitHub or curseforge)

**Comment by gbl** [comment]
Sure, you can! The mod is under the MIT license, which means as long as you're giving credits to where you got it from, you can do whatever you want with it.

**Comment by lkqyyds** [comment]
Thank U very much
